# Site settings
title: Eric Xie
motto: 坚持自律，砥砺前行
email: eric_xiett@163.com
description: > # this means to ignore newlines until "baseurl:"
  记录点滴成长，博客、杂记等等
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ericxiett.github.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ericxiett

# Build settings
markdown: kramdown
